"""Local-only review queue for Meeting to Action SFT targets."""

import json
import os
from pathlib import Path

import pandas as pd
import streamlit as st

from meeting_to_action.models import MeetingExtraction
from meeting_to_action.review import apply_review_edits, build_change_audit
from meeting_to_action.sft_enrichment import review_draft, save_review_packet

CASES_PATH = Path(os.getenv("SFT_CASES_PATH", "evaluation/sft-candidates.local.json"))
REVIEWS_PATH = Path(
    os.getenv("SFT_REVIEWS_PATH", "evaluation/reviewed_sft_extractions.local.json")
)


def editable_rows(items, fields):
    return [{field: getattr(item, field) for field in fields} for item in items]


def clean_rows(frame: pd.DataFrame | list[dict]) -> list[dict]:
    records = frame.to_dict(orient="records") if isinstance(frame, pd.DataFrame) else frame
    return [
        {key: None if pd.isna(value) else value for key, value in row.items()}
        for row in records
    ]


def load_inputs() -> tuple[dict[str, dict], dict[str, dict]]:
    cases = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    packet = json.loads(REVIEWS_PATH.read_text(encoding="utf-8"))
    case_by_id = {case["id"]: case for case in cases if case.get("split") == "development"}
    return case_by_id, packet


def show_evidence(extraction: MeetingExtraction) -> None:
    records = [
        *extraction.notes,
        *extraction.actions,
        *extraction.decisions,
        *extraction.open_questions,
    ]
    for record in records:
        label = next(
            (
                getattr(record, field)
                for field in ("title", "task", "summary", "question")
                if hasattr(record, field)
            ),
            record.id,
        )
        with st.expander(f"{record.id} · {label}"):
            for evidence in record.evidence:
                st.caption(f"Lines {evidence.line_start}-{evidence.line_end}")
                st.code(evidence.quote, language=None)


st.set_page_config(page_title="SFT Review Queue", page_icon="✓", layout="wide")
st.title("SFT Review Queue")
st.caption("Local review of AMI-derived targets. Drafts cannot enter training until approved.")

try:
    case_by_id, packet = load_inputs()
except (FileNotFoundError, json.JSONDecodeError) as error:
    st.error(f"Review data could not be loaded: {error}")
    st.stop()

status_counts = {
    status: sum(record.get("status") == status for record in packet.values())
    for status in ("draft", "approved", "rejected")
}
metrics = st.columns(4)
metrics[0].metric("Total", len(packet))
metrics[1].metric("Draft", status_counts["draft"])
metrics[2].metric("Approved", status_counts["approved"])
metrics[3].metric("Rejected", status_counts["rejected"])
st.progress(status_counts["approved"] / max(len(packet), 1), text="Approval progress")

with st.sidebar:
    reviewer = st.text_input("Reviewer", placeholder="name@example.com")
    status_filter = st.selectbox("Status", ["draft", "approved", "rejected", "all"])

eligible_ids = [
    source_id
    for source_id, record in sorted(packet.items())
    if status_filter == "all" or record.get("status") == status_filter
]
if not eligible_ids:
    st.success(f"No {status_filter} records remain.")
    st.stop()

source_id = st.selectbox(
    "Meeting",
    eligible_ids,
    format_func=lambda item: f"{item} · {case_by_id[item]['title']}",
)
case = case_by_id[source_id]
record = packet[source_id]
extraction = MeetingExtraction.model_validate(record["extraction"])

st.caption(
    f"Status: {record['status']} · Generated by {record.get('generated_by', 'unknown')} · "
    f"AMI meeting {case['source']['meeting_id']}"
)
transcript_column, target_column = st.columns([1, 1.25], gap="large")

with transcript_column:
    st.subheader("Source transcript")
    numbered = "\n".join(
        f"{index}: {line}" for index, line in enumerate(case["transcript"].splitlines(), 1)
    )
    st.code(numbered, language=None, line_numbers=False)
    st.subheader("Evidence")
    show_evidence(extraction)

with target_column:
    st.subheader("Training target")
    summary = st.text_area("Summary", extraction.summary, height=120, key=f"summary-{source_id}")
    notes = st.data_editor(
        editable_rows(extraction.notes, ("id", "title", "description")),
        disabled=["id"],
        hide_index=True,
        width="stretch",
        key=f"notes-{source_id}",
    )
    actions = st.data_editor(
        editable_rows(
            extraction.actions,
            ("id", "task", "owner", "deadline_text", "deadline", "status"),
        ),
        disabled=["id"],
        hide_index=True,
        width="stretch",
        key=f"actions-{source_id}",
    )
    decisions = st.data_editor(
        editable_rows(extraction.decisions, ("id", "summary", "rationale")),
        disabled=["id"],
        hide_index=True,
        width="stretch",
        key=f"decisions-{source_id}",
    )
    questions = st.data_editor(
        editable_rows(extraction.open_questions, ("id", "question", "owner")),
        disabled=["id"],
        hide_index=True,
        width="stretch",
        key=f"questions-{source_id}",
    )

    approve_column, reject_column = st.columns(2)
    approve = approve_column.button("Approve target", type="primary", width="stretch")
    reject = reject_column.button("Reject target", width="stretch")
    if approve or reject:
        try:
            reviewed = apply_review_edits(
                extraction,
                clean_rows(actions),
                clean_rows(decisions),
                clean_rows(questions),
                clean_rows(notes),
            ).model_copy(update={"summary": summary})
            audit = build_change_audit(extraction, reviewed)
            updated = review_draft(
                packet,
                source_id,
                reviewed,
                case["transcript"],
                reviewer,
                approved=approve,
            )
            updated["review_changes"] = audit
            save_review_packet(REVIEWS_PATH, packet)
            st.rerun()
        except (KeyError, ValueError) as error:
            st.error(error)